name: Build Tolibjon Production VST3

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.11.0

    - name: Download JUCE
      run: |
        git clone --depth 1 --branch master https://github.com/juce-framework/JUCE.git JUCE

    - name: Configure CMake
      run: cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release

    - name: Build VST3 Plugin
      run: cmake --build build --config Release --target TolibjonProduction_VST3

    - name: Upload VST3 Plugin Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Tolibjon-Production-VST3
        path: build/TolibjonProduction_artefacts/Release/VST3/
